[package]
name = "activity-2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.3"
merlin = "3.0.0"
rand = "0.8.5"
rand_core = "0.6.3"
schnorrkel = "0.10.2"
